#!/bin/bash
set -e
set -u
set -x

mkdir odoo
chown 104:107 ./odoo/

POSTGRES_PASSWORD=`tr -dc A-Za-z0-9_ < /dev/urandom | head -c 20 | xargs`
POSTGRES_USER=odoo

echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" > .env
echo "POSTGRES_USER=odoo" >> .env
